In [1]:
import pandas as pd

In [6]:
datasets = ['cont-village', 'cont-hospital', 'cont-workplace-13', 'cont-workplace-15', 
            'email-Enron', 'cont-primary-school', 'bills-senate', 'cont-high-school', 
            'bills-house', 'hosp-DAWN', 'coauth-dblp', 
            'clicks-trivago']

pred_datasets = ["cont-hospital", "cont-workplace-13", "cont-workplace-15", "hosp-DAWN", "bills-senate", 
                    "bills-house", "coauth-dblp", "cont-primary-school", "cont-high-school", 'email-Enron']
            
max_simplex_size = 8

In [7]:
results_arr = []
for dataset in datasets:
    curr_info = {'dataset': dataset}
    label_df = pd.read_csv(f"../ScoreData/{dataset}/labels.csv")
    curr_info['nodes'] = len(label_df)
    curr_info['classes'] = len(pd.unique(label_df['group_code']))
    
    for k in range(2, max_simplex_size + 1):
        filename = f"../ScoreData/{dataset}/size-{k}-unique-sorted.csv"
        with open(filename, 'r') as filehandle:
            counter = -1
            for line in filehandle:
                counter += 1
        if(k == 2):
            curr_info['edges'] = counter
            if(dataset in pred_datasets):
                with open(f'../LinkPredictionData/{dataset}/times.txt', 'r') as file:
                    tlines = file.readlines()
                curr_info['timesteps'] = len(pd.unique(tlines))
            else:
                curr_info['timesteps'] = 0
        elif(k == 3):
            curr_info['triangles'] = counter
        elif(k == 4):
            curr_info['tetrahedra'] = counter
        elif(k > 4):
            curr_info[f'groups of size {k}'] = counter
    results_arr.append(curr_info)

In [8]:
pd.DataFrame(results_arr)

,dataset,nodes,classes,edges,timesteps,triangles,tetrahedra,groups of size 5,groups of size 6,groups of size 7,groups of size 8
0,cont-village,46,5,327,0,582,572,386,175,46,5
1,cont-hospital,81,5,1380,12605,6078,9985,7802,3413,838,90
2,cont-workplace-13,100,5,3545,20129,14593,16929,11600,5000,1271,145
3,cont-workplace-15,232,12,13844,21536,59532,74909,54077,24480,6412,739
4,email-Enron,147,2,1298,10788,2076,2285,1639,739,191,22
5,cont-primary-school,242,11,14990,3124,102270,188994,161182,72983,18205,1993
6,bills-senate,294,2,17691,5048,103446,127887,85896,36204,8900,977
7,cont-high-school,332,9,26788,8938,105907,182849,177247,97456,28705,3557
8,bills-house,1494,2,101066,4929,226725,230127,151852,64409,15960,1759
9,hosp-DAWN,2558,364,87150,32,340364,420503,257976,98017,22141,2279
10,coauth-dblp,105256,2,267332,55,236507,140513,62719,20016,4018,380
11,clicks-trivago,172738,160,662337,0,677434,512995,287421,109780,25286,2642